name: flutter_vrt_sample
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/NotoSansJP-Medium.otf
